version: '3.8'
services:
  cee-hacks-2020-images-db:
    container_name: cee-hacks-2020-images-db
    image: postgres:13.0
    env_file:
      - .env.prod
    ports:
      - 5442:5432
    volumes:
      - cee-hacks-2020-images-db:/var/lib/postgresql/data/
    networks:
      - cee-hacks-2020-images

  cee-hacks-2020-images-minio:
    container_name: cee-hacks-2020-images-minio
    image: minio/minio:RELEASE.2020-11-13T20-10-18Z
    env_file:
      - .env.prod
    ports:
      - 9010:9000
    volumes:
      - cee-hacks-2020-images-minio:/data
    command: server /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
    networks:
      - cee-hacks-2020-images

  cee-hacks-2020-images-backend:
    container_name: cee-hacks-2020-images-backend
    image: mildblue/cee-hacks-2020-images-backend
    env_file:
      - .env.prod
    ports:
      - 8090:8080
    restart: always
    depends_on:
      - cee-hacks-2020-images-db
      - cee-hacks-2020-images-minio
    networks:
      - cee-hacks-2020-images

  cee-hacks-2020-images-worker:
    container_name: cee-hacks-2020-images-worker
    image: mildblue/cee-hacks-2020-images-worker
    env_file:
      - .env.prod
    restart: always
    depends_on:
      - cee-hacks-2020-images-db
      - cee-hacks-2020-images-minio
    networks:
      - cee-hacks-2020-images

volumes:
  cee-hacks-2020-images-db:
  cee-hacks-2020-images-minio:

networks:
  cee-hacks-2020-images:
    driver: bridge